
#include "../templates/include.pml"

init{

	nodes[1].id = 1; 
nodes[1].name = 1; 
nodes[1].cpu = 32; 
nodes[1].memory = 64; 
nodes[1].cpuLeft = 16; 
nodes[1].memLeft = 32; 
nodes[1].numPod = 2; 
nodes[1].status = 1; 
nodes[1].labelKeyValue[0] = 1; 
nodes[1].labelKeyValue[1] = 0; 
nodes[1].labelKeyValue[2] = 1; 
nodes[1].score = 0; 
nodes[1].curScore = 0; 
nodes[1].curAffinity = 0; 
nodes[1].curTaint = 0; 
nodes[2].id = 2; 
nodes[2].name = 2; 
nodes[2].cpu = 32; 
nodes[2].memory = 64; 
nodes[2].cpuLeft = 24; 
nodes[2].memLeft = 48; 
nodes[2].numPod = 1; 
nodes[2].status = 1; 
nodes[2].labelKeyValue[0] = 2; 
nodes[2].labelKeyValue[1] = 0; 
nodes[2].labelKeyValue[2] = 1; 
nodes[2].score = 0; 
nodes[2].curScore = 0; 
nodes[2].curAffinity = 0; 
nodes[2].curTaint = 0; 
nodes[3].id = 3; 
nodes[3].name = 3; 
nodes[3].cpu = 32; 
nodes[3].memory = 64; 
nodes[3].cpuLeft = 16; 
nodes[3].memLeft = 32; 
nodes[3].numPod = 2; 
nodes[3].status = 1; 
nodes[3].labelKeyValue[0] = 3; 
nodes[3].labelKeyValue[1] = 0; 
nodes[3].labelKeyValue[2] = 2; 
nodes[3].score = 0; 
nodes[3].curScore = 0; 
nodes[3].curAffinity = 0; 
nodes[3].curTaint = 0; 
pods[1].id = 4; 
pods[1].loc = 1; 
pods[1].workloadType = 1; 
pods[1].workloadId = 1; 
pods[1].podTemplateId = 1; 
pods[1].status = 1; 
pods[1].cpu = 8; 
pods[1].memory = 16; 
pods[1].important = 0; 
pods[1].score = 0; 
pods[2].id = 5; 
pods[2].loc = 1; 
pods[2].workloadType = 1; 
pods[2].workloadId = 1; 
pods[2].podTemplateId = 1; 
pods[2].status = 1; 
pods[2].cpu = 8; 
pods[2].memory = 16; 
pods[2].important = 0; 
pods[2].score = 0; 
pods[3].id = 6; 
pods[3].loc = 2; 
pods[3].workloadType = 1; 
pods[3].workloadId = 1; 
pods[3].podTemplateId = 1; 
pods[3].status = 1; 
pods[3].cpu = 8; 
pods[3].memory = 16; 
pods[3].important = 0; 
pods[3].score = 0; 
pods[4].id = 7; 
pods[4].loc = 3; 
pods[4].workloadType = 1; 
pods[4].workloadId = 1; 
pods[4].podTemplateId = 1; 
pods[4].status = 1; 
pods[4].cpu = 8; 
pods[4].memory = 16; 
pods[4].important = 0; 
pods[4].score = 0; 
pods[5].id = 8; 
pods[5].loc = 3; 
pods[5].workloadType = 1; 
pods[5].workloadId = 1; 
pods[5].podTemplateId = 1; 
pods[5].status = 1; 
pods[5].cpu = 8; 
pods[5].memory = 16; 
pods[5].important = 0; 
pods[5].score = 0; 
pods[6].id = 9; 
pods[6].loc = 4; 
pods[6].workloadType = 1; 
pods[6].workloadId = 1; 
pods[6].podTemplateId = 1; 
pods[6].status = 0; 
pods[6].cpu = 8; 
pods[6].memory = 16; 
pods[6].important = 0; 
pods[6].score = 0; 
d[1].id = 10; 
d[1].status = 1; 
d[1].curVersion = 0; 
d[1].minReplicas = 5; 
d[1].specReplicas = 5; 
d[1].replicas = 5; 
d[1].maxReplicas = 12; 
d[1].podTemplateId = 1; 
d[1].maxSurge = 25; 
d[1].maxUnavailable = 25; 
d[1].strategy = 1; 
d[1].replicaSets[0].id = 11; 
d[1].replicaSets[0].deploymentId = 1; 
d[1].replicaSets[0].replicas = 5; 
d[1].replicaSets[0].specReplicas = 5; 
d[1].replicaSets[0].version = 0; 
d[1].replicaSets[0].podIds[0] = 1; 
d[1].replicaSets[0].podIds[1] = 2; 
d[1].replicaSets[0].podIds[2] = 3; 
d[1].replicaSets[0].podIds[3] = 4; 
d[1].replicaSets[0].podIds[4] = 5; 
d[1].replicaSets[0].podIds[5] = 0; 
d[1].replicaSets[1].id = 12; 
d[1].replicaSets[1].deploymentId = 1; 
d[1].replicaSets[1].replicas = 0; 
d[1].replicaSets[1].specReplicas = 0; 
d[1].replicaSets[1].version = 0; 
d[1].replicaSets[1].podIds[0] = 0; 
d[1].hpaSpec.isEnabled = 1; 
d[1].hpaSpec.numMetrics = 1; 
d[1].hpaSpec.metricNames[0] = 0; 
d[1].hpaSpec.metricTargets[0] = 100; 
d[1].hpaSpec.metricTypes[0] = 1; 
podTemplates[1].cpuRequested = 8; 
podTemplates[1].memRequested = 16; 
podTemplates[1].numTopoSpreadConstraints = 2; 
podTemplates[1].numRules = 0; 
podTemplates[1].nodeName = 0; 
podTemplates[1].numNoScheduleNode = 0; 
podTemplates[1].numPreferNoScheduleNode = 0; 
podTemplates[1].labelKeyValue[0] = 0; 
podTemplates[1].labelKeyValue[1] = 0; 
podTemplates[1].labelKeyValue[2] = 1; 
podTemplates[1].labelKeyValue[3] = 0; 
podTemplates[1].topoSpreadConstraints[0].maxSkew = 1; 
podTemplates[1].topoSpreadConstraints[0].minDomains = 2; 
podTemplates[1].topoSpreadConstraints[0].topologyKey = 0; 
podTemplates[1].topoSpreadConstraints[0].whenUnsatisfiable = 0; 
podTemplates[1].topoSpreadConstraints[0].numMatchedLabel = 1; 
podTemplates[1].topoSpreadConstraints[0].labelKey[0] = 2; 
podTemplates[1].topoSpreadConstraints[0].labelKey[1] = 0; 
podTemplates[1].topoSpreadConstraints[0].labelValue[0] = 1; 
podTemplates[1].topoSpreadConstraints[0].labelValue[1] = 0; 
podTemplates[1].topoSpreadConstraints[0].nodeAffinityPolicy = 1; 
podTemplates[1].topoSpreadConstraints[0].nodeTaintsPolicy = 0; 
podTemplates[1].topoSpreadConstraints[1].maxSkew = 1; 
podTemplates[1].topoSpreadConstraints[1].minDomains = 2; 
podTemplates[1].topoSpreadConstraints[1].topologyKey = 2; 
podTemplates[1].topoSpreadConstraints[1].whenUnsatisfiable = 0; 
podTemplates[1].topoSpreadConstraints[1].numMatchedLabel = 1; 
podTemplates[1].topoSpreadConstraints[1].labelKey[0] = 2; 
podTemplates[1].topoSpreadConstraints[1].labelKey[1] = 0; 
podTemplates[1].topoSpreadConstraints[1].labelValue[0] = 1; 
podTemplates[1].topoSpreadConstraints[1].labelValue[1] = 0; 
podTemplates[1].topoSpreadConstraints[1].nodeAffinityPolicy = 1; 
podTemplates[1].topoSpreadConstraints[1].nodeTaintsPolicy = 0; 

	
	run deployment_controller();
	run scheduler();
	run hpa();
	
	run eventCpuChange(1); 


	

	int i = 1;
	for (i : 1 .. NODE_NUM) {
		run nodeController(i);
		run kernelPanic(i);
	}
}